import { createCacheClient } from "@/lib/supabase/cache-client";
import AtlasClient from "./atlas-client";

export const metadata = { title: "Inventory Atlas" };

export type Proc = "make" | "trade" | null;
export type AtlasCat = {
  id: string;
  name: string;
  parent_id: string | null;
  /** Category default Make/Trade (null = inherits from parent at the app level). */
  procurement_type: Proc;
};
export type AtlasItem = {
  id: string;
  code: string;
  name: string;
  item_type: string;
  category_id: string;
  in_r1: boolean;
  /** The item's OWN Make/Trade override (null = inherit from its category). */
  procurement_type: Proc;
  /** Total on-hand stock summed across warehouses. */
  stock: number;
  /** Produced by an audited program (a component/cut_part output of one), OR a
   *  sub-assembly whose MAKE child parts are all captured by audited programs. */
  programmed: boolean;
  /** Its demand is generated by a demand rule — it's the CHILD of a component rule
   *  (item_demand_rules) or the target of an active demand formula. */
  demand_rule: boolean;
};
export type AtlasUnit = { id: string; name: string };

async function fetchData(): Promise<{
  categories: AtlasCat[];
  items: AtlasItem[];
  units: AtlasUnit[];
  r1TouchedCats: string[];
}> {
  const sb = createCacheClient();

  // ── All categories (small) ──────────────────────────────────────────────
  const { data: cats } = await sb
    .from("item_categories")
    .select("id, name, parent_id, procurement_type");
  const allCats: AtlasCat[] = cats ?? [];

  // Cabin lives in its own surface — exclude its whole subtree here.
  const cabinRoot = allCats.find((c) => c.name === "Cabin" && c.parent_id === null);
  const cabinIds = new Set<string>();
  if (cabinRoot) {
    const queue = [cabinRoot.id];
    while (queue.length) {
      const id = queue.shift()!;
      cabinIds.add(id);
      allCats.filter((c) => c.parent_id === id).forEach((c) => queue.push(c.id));
    }
  }
  const categories = allCats.filter((c) => !cabinIds.has(c.id));

  const cabinFilter = cabinIds.size > 0 ? `(${[...cabinIds].join(",")})` : null;

  // The six blocks below don't read each other's results (only the items query
  // needed the categories above, for the cabin filter) — fetch them concurrently.

  // ── What R1 references, in one paged scan over all lines ──────────────────
  // r1Set      = item ids picked on a line (specific item).
  // r1CatSet   = category ids picked on a line (the category dropdown). A line
  //              often has a category but NO specific item, so a sub-category
  //              counts as "touched" even when no item slot was filled.
  const r1Promise = (async () => {
    const r1Set = new Set<string>();
    const r1CatSet = new Set<string>();
    const { count } = await sb
      .from("packing_r1_lines")
      .select("id", { count: "exact", head: true });
    const pages = Math.max(1, Math.ceil((count ?? 0) / 1000));
    const results = await Promise.all(
      Array.from({ length: pages }, (_, i) =>
        sb
          .from("packing_r1_lines")
          .select("item_id, category_id")
          .range(i * 1000, (i + 1) * 1000 - 1),
      ),
    );
    for (const r of results) {
      for (const row of (r.data ?? []) as { item_id: string | null; category_id: string | null }[]) {
        if (row.item_id) r1Set.add(row.item_id);
        if (row.category_id) r1CatSet.add(row.category_id);
      }
    }
    return { r1Set, r1CatSet };
  })();

  // ── Stock per item (summed across warehouses; paged past the 1000 cap) ─────
  const stockPromise = (async () => {
    const stockByItem = new Map<string, number>();
    const { count } = await sb
      .from("inventory")
      .select("item_id", { count: "exact", head: true });
    const pages = Math.max(1, Math.ceil((count ?? 0) / 1000));
    const res = await Promise.all(
      Array.from({ length: pages }, (_, i) =>
        sb.from("inventory").select("item_id, quantity").range(i * 1000, (i + 1) * 1000 - 1),
      ),
    );
    for (const r of res)
      for (const row of (r.data ?? []) as { item_id: string; quantity: number }[])
        stockByItem.set(row.item_id, (stockByItem.get(row.item_id) ?? 0) + Number(row.quantity || 0));
    return stockByItem;
  })();

  // ── Items produced by an AUDITED program (component/cut_part outputs) ───────
  const programmedPromise = (async () => {
    const programmedSet = new Set<string>();
    // The audited-ops list and the outputs count are independent — fire both;
    // the outputs PAGE fetches stay gated on having any audited program at all.
    const [opsRes, countRes] = await Promise.all([
      sb.from("operations").select("id").not("audited_at", "is", null),
      sb.from("operation_outputs").select("id", { count: "exact", head: true }),
    ]);
    const auditedSet = new Set<string>((opsRes.data ?? []).map((o) => o.id as string));
    if (auditedSet.size > 0) {
      const pages = Math.max(1, Math.ceil((countRes.count ?? 0) / 1000));
      const res = await Promise.all(
        Array.from({ length: pages }, (_, i) =>
          sb
            .from("operation_outputs")
            .select("item_id, role, operation_id")
            .range(i * 1000, (i + 1) * 1000 - 1),
        ),
      );
      for (const r of res)
        for (const row of (r.data ?? []) as {
          item_id: string | null;
          role: string;
          operation_id: string;
        }[])
          if (
            row.item_id &&
            (row.role === "component" || row.role === "cut_part") &&
            auditedSet.has(row.operation_id)
          )
            programmedSet.add(row.item_id);
    }
    return programmedSet;
  })();

  // ── Parts lists (item_bom_lines), for the sub-assembly "programmed" rule:
  //    a sub-assembly counts as program-covered when ALL its MAKE children are
  //    audited-program outputs (trade children are bought, not cut). ───────────
  const bomLinesPromise = (async () => {
    const rows: { parent_item_id: string; child_item_id: string }[] = [];
    const { count } = await sb
      .from("item_bom_lines")
      .select("id", { count: "exact", head: true });
    const pages = Math.max(1, Math.ceil((count ?? 0) / 1000));
    const res = await Promise.all(
      Array.from({ length: pages }, (_, i) =>
        sb
          .from("item_bom_lines")
          .select("parent_item_id, child_item_id")
          .range(i * 1000, (i + 1) * 1000 - 1),
      ),
    );
    for (const r of res)
      for (const row of (r.data ?? []) as { parent_item_id: string | null; child_item_id: string | null }[])
        if (row.parent_item_id && row.child_item_id)
          rows.push({ parent_item_id: row.parent_item_id, child_item_id: row.child_item_id });
    return rows;
  })();

  // ── Items whose demand comes from a demand rule (child of a component rule,
  //    or target of an active demand formula). Small tables — one read each. ────
  const demandRulePromise = (async () => {
    const set = new Set<string>();
    const [comp, formulas] = await Promise.all([
      sb.from("item_demand_rules").select("child_item_id"),
      sb.from("demand_formulas").select("target_item_id").eq("is_active", true),
    ]);
    for (const r of (comp.data ?? []) as { child_item_id: string | null }[])
      if (r.child_item_id) set.add(r.child_item_id);
    for (const r of (formulas.data ?? []) as { target_item_id: string | null }[])
      if (r.target_item_id) set.add(r.target_item_id);
    return set;
  })();

  // ── Non-cabin active items (10 parallel pages → up to 10k) ─────────────────
  const itemPagesPromise = Promise.all(
    Array.from({ length: 10 }, (_, i) => {
      let q: any = sb
        .from("items")
        .select("id, code, name, item_type, category_id, procurement_type")
        .eq("is_active", true)
        .not("category_id", "is", null)
        .range(i * 1000, (i + 1) * 1000 - 1)
        .order("name");
      if (cabinFilter) q = q.not("category_id", "in", cabinFilter);
      return q;
    }),
  );

  // ── Units (for the create-item modal) ──────────────────────────────────────
  const unitsPromise = sb
    .from("units_of_measurement")
    .select("id, name")
    .order("name");

  const [{ r1Set, r1CatSet }, stockByItem, programmedSet, bomLines, demandRuleSet, itemPages, unitsRes] =
    await Promise.all([
      r1Promise,
      stockPromise,
      programmedPromise,
      bomLinesPromise,
      demandRulePromise,
      itemPagesPromise,
      unitsPromise,
    ]);

  const rawItems: any[] = itemPages.flatMap((p: any) => p.data ?? []);

  // Sub-assembly coverage: a parent counts as "programmed" when it has at least
  // one MAKE child and every MAKE child is program-covered (directly, or itself
  // a covered sub-assembly — hence the fixpoint). Trade children are bought.
  const itemProc = new Map<string, Proc>(rawItems.map((i) => [i.id, i.procurement_type ?? null]));
  const itemCat = new Map<string, string | null>(rawItems.map((i) => [i.id, i.category_id ?? null]));
  const catById = new Map(allCats.map((c) => [c.id, c]));
  const effCatProc = (catId: string | null): Proc => {
    let cur = catId ? catById.get(catId) : undefined;
    for (let depth = 0; cur && depth < 10; depth++) {
      if (cur.procurement_type) return cur.procurement_type;
      cur = cur.parent_id ? catById.get(cur.parent_id) : undefined;
    }
    return null;
  };
  const isTrade = (itemId: string): boolean =>
    (itemProc.get(itemId) ?? effCatProc(itemCat.get(itemId) ?? null)) === "trade";

  const childrenByParent = new Map<string, string[]>();
  for (const l of bomLines) {
    const a = childrenByParent.get(l.parent_item_id) ?? [];
    a.push(l.child_item_id);
    childrenByParent.set(l.parent_item_id, a);
  }
  let changed = true;
  while (changed) {
    changed = false;
    for (const [parent, children] of childrenByParent) {
      if (programmedSet.has(parent)) continue;
      const makeKids = children.filter((ch) => !isTrade(ch));
      if (makeKids.length > 0 && makeKids.every((ch) => programmedSet.has(ch))) {
        programmedSet.add(parent);
        changed = true;
      }
    }
  }

  const items: AtlasItem[] = rawItems.map((i: any) => ({
    ...i,
    in_r1: r1Set.has(i.id),
    stock: stockByItem.get(i.id) ?? 0,
    programmed: programmedSet.has(i.id),
    demand_rule: demandRuleSet.has(i.id),
  }));

  return { categories, items, units: unitsRes.data ?? [], r1TouchedCats: [...r1CatSet] };
}

export default async function InventoryAtlasPage() {
  const { categories, items, units, r1TouchedCats } = await fetchData();
  return (
    <AtlasClient
      categories={categories}
      items={items}
      units={units}
      r1TouchedCats={r1TouchedCats}
    />
  );
}
